version: '3.8'

services:
  flask-app:
    build:
      context: ..
      dockerfile: flask-server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../client-customer/build:/client-customer/build
      - ../client-admin/build:/client-admin/build
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=shoppingonline
      - PORT=3000
      - BREVO_API_KEY=${BREVO_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
