version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=shoppingonline
      - PORT=3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
